- name: Deploy with Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: Ensure Docker is running
      shell: systemctl start docker
      ignore_errors: yes

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Pull images via Docker Compose
      shell: docker compose pull
      args:
        chdir: /opt

    - name: Run Docker Compose
      shell: docker compose up -d
      args:
        chdir: /opt


