version: '3'

services:
  backend:
    container_name: calc-backend
    image: deepanshu0903/calc-backend:latest
    ports:
      - "8000:8000"

  frontend:
    container_name: calc-frontend
    image: deepanshu0903/calc-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"

